export const Data = [
  {
    id: "1",
    name: "Trade and Make Money",
    img1: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Fcourse-pics%2Fnew%2Ftrade.png&w=2048&q=75",
    img2: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Ffacilitator-pics%2Fnew%2Fchris2.png&w=2048&q=75",
    author: "Chris Ani",
    lessons: "8",
    price: "116,200.00",
  },
  {
    id: "2",
    name: "Video Production MasterClass",
    img1: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Fcourse-pics%2Fnew%2Fvideo.png&w=2048&q=75",
    img2: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Ffacilitator-pics%2Fnew%2Fransome.png&w=2048&q=75",
    author: "Ransome Adewale",
    lessons: "10",
    price: "29,050.00",
  },
  {
    id: "3",
    name: "Affiliate Marketing Mastery Course",
    img1: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Fcourse-pics%2Fnew%2Faffiliate.png&w=2048&q=75",
    img2: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Ffacilitator-pics%2Fnew%2Fchigozie.png&w=2048&q=75",
    author: "Chigozie Emmanuel",
    lessons: "10",
    price: "41,500.00",
  },
  {
    id: "4",
    name: "Cake Baking And Decoration",
    img1: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Fcourse-pics%2Fnew%2Fcake.png&w=2048&q=75",
    img2: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Ffacilitator-pics%2Fnew%2Fblessing.png&w=2048&q=75",
    author: "Blessing Umeh",
    lessons: "10",
    price: "46,687.50",
  },
  {
    id: "5",
    name: "Deasign And Earn MasterClass",
    img1: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Fcourse-pics%2Fnew%2Fdesign.png&w=2048&q=75",
    img2: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Ffacilitator-pics%2Fnew%2Fmoski.png&w=2048&q=75",
    author: "Adewale Moski",
    lessons: "10",
    price: "51,875.00",
  },
  {
    id: "6",
    name: "Trade and Make Money",
    img1: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Fcourse-pics%2Fnew%2Fwhatsapp.png&w=2048&q=75",
    img2: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Ffacilitator-pics%2Fnew%2Fchris2.png&w=2048&q=75",
    author: "Chris Ani",
    lessons: "10",
    price: "10,375.00",
  },
  {
    id: "7",
    name: "Drone Piloting and Business Course",
    img1: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Fcourse-pics%2Fnew%2Fdrone.png&w=2048&q=75",
    img2: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Ffacilitator-pics%2Fnew%2Fdavid.png&w=2048&q=75",
    author: "David Opateyibo",
    lessons: "10",
    price: "46,687.50",
  },
  {
    id: "8",
    name: "User Interface and Experience Design(UI/UX)",
    img1: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Fcourse-pics%2Fnew%2Fui.png&w=2048&q=75",
    img2: "https://blog.daba.school/_next/image?url=https%3A%2F%2Fchrisani.com%2Fdaba-api%2Ffacilitator-pics%2Fnew%2Fmoski.png&w=2048&q=75",
    author: "Adewale Moski",
    lessons: "10",
    price: "72,625.00",
  },
];

export default Data;
